### ISSUE TITLE
trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/redaxo_loader#13]
Aus Slack.
Vermutlich betreffend Strato wenn curl nicht verfügbar:

Alexplus:
>https://github.com/FriendsOfREDAXO/redaxo_loader/blob/df7a2cca4641e3511ddb6e4b3e5d4af8bf8aa5a1/redaxo_loader.php#L116
Hier kommt ein leeres Ergebnis raus, das später nicht ordentlich geprüft wird. Vermutlich ist curl o.ä. auf dem Server deaktiviert.
Du fragst später if($releases), aber die Variable ist ja immer ein Array, wenn auch leer.
müsste trotzdem später ein leeres Array abgefragt werden und so.

![image](https://user-images.githubusercontent.com/16903055/117981190-085ec800-b335-11eb-9ce9-dbf0d7e52a59.png)
![image (1)](https://user-images.githubusercontent.com/16903055/117981201-0ac12200-b335-11eb-8f02-3dfdec1aa332.png)

**Comment by danspringer** [comment]
Siehe auch #12

**Comment by skerbis** [comment]
am besten vorher schon checken ob curl vorh.

**Comment by AWqxKAWERbXo** [comment]
![image](https://user-images.githubusercontent.com/3855487/213296510-7d0f5e05-d2a4-4499-b67c-3dde27d7d1ee.png)

funktioniert trotzdem nicht.

**Comment by skerbis** [comment]
Die Strato-IP ist von Github geblockt. Der Check der Limits ist aber nicht korrekt.

**Comment by AWqxKAWERbXo** [comment]
D.h. jetzt geht das wieder oder bleibt die Sperre?

**Comment by aeberhard** [comment]
@alxndr-w Die Sperre liegt am Github-API Limit.
Das liegt bei 60 Aufrufen pro Stunde (pro IP-Adresse) Das ist bei Strato schnell aufgebraucht.

PR kommt demnächst :)

**Comment by AWqxKAWERbXo** [comment]
Verstehe.

**Comment by skerbis** [comment]
gefixt wurde nur die Fehlermeldung, die irreführend war
