### ISSUE TITLE
sicherheit verbessern

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/redaxo_loader#2]
- aktuell kann via GET parameter [jede beliebige Datei via Url auf den Server geladen](https://github.com/FriendsOfREDAXO/redaxo_loader/blob/2657cfb0c9cb6b1eb68eb039e26188710933d398/redaxo_loader.php#L39) werden. dies sollte eingeschränkt werden auf urls die mit `'https://api.github.com/repos/' . REPO . '` beginnen
- der loader sollte sich selbst zerstören nach erfolgreichem setup, damit er nicht vergessen bleibt und als backdoor genutzt werden kann
- sollte der loader eine art token verwenden, sodass man ihn nur darüber verwenden kann?
- macht es sinn die heruntergeladenen redaxo releases mit einer checksum gegenzuprüfen?

**Comment by skerbis** [comment]
- das Alter der loader datei sollte überprüft werden, Ausführung sperren nach X Minuten?
- Der filename sollte überprüft werden (z.B. nicht index.php

**Comment by skerbis** [comment]
@danspringer 

das muss noch irgendwo rein. Aber durch das Ajax komme ich da nicht hin. 

```php
	if (isset($_GET['url'])
       {
	$pos = strpos('https://github.com/redaxo/redaxo/releases/', $_GET['url']);
        if(false == $pos)
        {
          echo 'Ungültige Download-URL übergeben';  
        }
       }
```

**Comment by skerbis** [comment]
@staabm 

zu 1. 
https://github.com/FriendsOfREDAXO/redaxo_loader/blob/59be9bdee4412425a1258a94e9cca35e1a2b896e/redaxo_loader.php#L48

zu 2. 
https://github.com/FriendsOfREDAXO/redaxo_loader/blob/59be9bdee4412425a1258a94e9cca35e1a2b896e/redaxo_loader.php#L104

zu 3. 
Denke nicht. 

zu 4. 
PR Welcome 😀

> Der filename sollte überprüft werden (z.B. nicht index.php

https://github.com/FriendsOfREDAXO/redaxo_loader/blob/59be9bdee4412425a1258a94e9cca35e1a2b896e/redaxo_loader.php#L25

**Comment by danspringer** [comment]
Hier kann man vorerst schliessen.
1, 2 und 3 wurden entsprechend besprochen und 1 und 2 umgesetzt.
