### ISSUE TITLE
Add-on Loader

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/redaxo_loader#5]
Es sollte möglich sein, Addons gleich mit herunterzuladen.

**Comment by novinet-dsteffen** [comment]
Dazu habe ich doch bereits ein addon geschrieben ;-)
https://github.com/novinet-git/nv_defaultaddons
Könnte man vielleicht irgendwie "verwurschteln"

**Comment by AWqxKAWERbXo** [comment]
@novinet-dsteffen achso, dachte, das wird nicht mehr gewartet. https://github.com/novinet-git/nv_defaultaddons/pulls

**Comment by skerbis** [comment]
Der redaxo_loader ist ein Hilfe für die Leute die häufig Probleme mit lahmen FTP-Verbindungen haben und keinen Konsolen-Zugriff haben. Ich würde diese Funktion hier nicht unterbringen.

**Comment by novinet-dsteffen** [comment]
> @novinet-dsteffen achso, dachte, das wird nicht mehr gewartet. https://github.com/novinet-git/nv_defaultaddons/pulls

oh, danke! nein, wird natürlich gewartet. ich werde das mit reinbringen für den nächsten release
