### ISSUE TITLE
Fehlerhandling verbessern

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/redaxo_loader#6]
- curl scheint vorraussetzung und wird nicht geprüft 
- allow_url_fopen scheint vorraussetzung zu sein, https://www.php.net/manual/de/features.remote-files.php
- Zip extension scheint vorraussetzung zu sein, https://www.php.net/manual/en/class.ziparchive.php

**Comment by skerbis** [comment]
zu url_fopen: https://github.com/FriendsOfREDAXO/redaxo_loader/pull/7
