### ISSUE TITLE
Api limit auswerten

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/redaxo_loader#9]
Github liefert einen http response header in dem steht wie oft man noch aufrufen darf

siehe https://github.com/KnpLabs/php-github-api/blob/40571b9298b14244a77df50bef06dc510cd4ffa7/lib/Github/HttpClient/Message/ResponseMediator.php#L61

sobald das limit erreicht ist sollte eine ordentliche Fehlermeldung kommen.. 

Stand heute kommt vermutlich

Notice: Trying to get property 'id' of non-object in /mnt/web509/c0/51/xxx/htdocs/hml/2103/redaxo_loader.php on line 225 
Notice: Trying to get property 'id' of non-object in /mnt/web509/c0/51/xxx/htdocs/hml/2103/redaxo_loader.php on line 225

**Comment by staabm** [comment]
An die response header kommt man drann mit https://stackoverflow.com/a/41135574

**Comment by danspringer** [comment]
Danke

**Comment by danspringer** [comment]
Wurde mit https://github.com/FriendsOfREDAXO/redaxo_loader/pull/10 behandelt.
